version: 0.0
os: linux
files:
 - source: /
   destination: /home/ec2-user/devop/HelloDevOp/

hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3000
      runas: root

   
